# Generated by Django 3.2.19 on 2023-12-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "0377_flatpersonoverride"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="strapi_id",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
